export enum DrawType {
  /** 点 */
  Point = 'Point',
  /** 告警点 */
  AlarmPoint = 'AlarmPoint',
  /** 图片点 */
  ImagePoint = 'ImagePoint',
  /** 线 */
  Line = 'LineString',
  /** 流动线 */
  FlowLine = 'FlowLine',
  /** 自由线 */
  FreehandLine = 'FreehandLine',
  /** 自由面 */
  FreehandPolygon = 'FreehandPolygon',
  /** 多边形 */
  Polygon = 'Polygon',
  /** 矩形 */
  Rectangle = 'Rectangle',
  /** 圆 */
  Circle = 'Circle',
  /** 椭圆 */
  Ellipse = 'Ellipse',
  /** 扇形 */
  Sector = 'Sector',
  /** 直箭头 */
  StraightArrow = 'StraightArrow',
  /** 渐缩箭头 */
  TaperedArrow = 'TaperedArrow',
  /** 线箭头 */
  LineArrow = 'LineArrow',
  /** 双箭头 */
  DoubleArrow = 'DoubleArrow',
  /** 弓形 */
  Arc = 'Arc',
  /** 旗帜 */
  Flag = 'Flag',
  /** 测距 */
  Measure = 'Measure',
  /** 方位角 */
  Azimuth = 'Azimuth',
  AreaMeasure = 'AreaMeasure',
}
